version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.2
    - 5.12.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: flexiblepersistence
    versions:
    - 1.3.1
    - 1.3.2
    - 1.3.3
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
